- hosts: webserver
  become: yes
  become_method: sudo
  connection: local

  tasks:
    - name: Get stuff from git
      git:
       repo: https://github.com/liphinstanley/Adjust
       dest: /tmp/web_app/
      delegate_to: localhost

    - name: Build webapp image
      ansible.builtin.command:
        cmd: cd /tmp/web_app/docker && docker build -t adjust_webapp .
    
    - name: install webapp helm chart
      ansible.builtin.command:
        cmd: cd /tmp/web_app/web-app/helmchart && helm install web_app . 

