- hosts: webserver
  become: yes
  become_method: sudo
  connection: local

  tasks:
    - name: Get stuff from git
      git:
       repo: https://github.com/liphinstanley/Adjust
       dest: /tmp/web_app/

    - name: Build webapp image
      ansible.builtin.command:
        cmd: docker build -t adjust_webapp /tmp/web_app/docker
    
    - name: install webapp helm chart
      ansible.builtin.command:
        cmd: helm install web_app /tmp/web_app/helmcharts/web-app 

